[package]
name = "ssr-server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ssr-core = { workspace = true }
ssr-protocol = { workspace = true, features = ["net"] }
bevy = { workspace = true }
lightyear = { workspace = true }
serde = { workspace = true }
avian2d = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ron = { workspace = true }
